#:kivy 1.0

<SpecialPoint>:
	lbl: lbl

	canvas:
		Color:
			rgb: self.pcolor
		Point:
			pointsize: 2
			points: self.pos
		Color:
			rgba: self.lcolor
		Line:
			dash_length: 5
			dash_offset: 10
			width: self.lnw
			points: ( 0, self.pos[1], self.width, self.pos[1] )
		Line:
			dash_length: 5
			dash_offset: 10
			width: self.lnw
			points: ( self.pos[0], 0, self.pos[0], self.height )
	Label:
		id: lbl
		size: 30, 30
		pos: self.parent.pos
